config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start_date, :end_date, :all_day, :memo))
    if @schedule.save
      flash[:notice] = "スケジュールを新規登録しました"
      redirect_to :schedules
    else
      render "new"
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start_date, :end_date, :all_day, :memo))
      flash[:notice] = "スケジュールを更新しました"
      redirect_to :schedules
    else
      render "edit"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to action: :index, status: 303
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<%= render "shared/header" %>

<h3>スケジュール編集</h3>
<%= form_with model: @schedule do |f| %>
<table>
    <tr>
        <th><%= f.label :title ,"タイトル" %></th>
        <td><%= f.text_field :title %></td>
    </tr>
    <tr>
        <th><%= f.label :start_date ,"開始日" %></th>
        <td><%= f.date_select :start_date %></td>
    </tr>
    <tr>
        <th><%= f.label :end_date ,"終了日" %></th>
        <td><%= f.date_select :end_date %></td>
    </tr>
    <tr>
        <th><%= f.label :all_day ,"終日" %></th>
        <td><%= f.check_box :all_day %>
            <p>※終日の場合はチェックを入れます</p>
        </td>
    </tr>
    <tr>
        <th><%= f.label :memo ,"スケジュールメモ" %></th>
        <td><%= f.text_area :memo %></td>
    </tr>
</table>

<div>
    <ul>
        <li><%= f.submit "編集を完了する"%></li>
        <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
    </ul>
</div>
<% end %>

<%= render "shared/footer" %>

app/views/schedules/index.html.erb
<%= render "shared/header" %>

<h3>スケジュール一覧</h3>

<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>タイトル</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>終日</th>
            <th>スケジュール更新日時</th>
            <th>確認</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>

    <tbody>
        <% @schedules.each do |schedule| %>
        <tr>
            <td><%= schedule.id %></td>
            <td><%= schedule.title %></td>
            <td><%= schedule.start_date %></td>
            <td><%= schedule.end_date %></td>
            <td><%if schedule.all_day == true %>
                ○
                <% else schedule.all_day == false %>
                <% end %>
            </td>
            <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
            <td>
                <%= link_to "確認", schedule_path(schedule.id) %>
            </td>
            <td>
                <%= link_to "編集", [:edit, schedule] %>
            </td>
            <td>
                <%= link_to "削除", schedule, data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }%>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to "スケジュール新規登録", :new_schedule %></p>

<%= render "shared/footer" %>

app/views/schedules/new.html.erb
<h3>スケジュール新規作成</h3>

<%= form_with model: @schedule do |f| %>
<table>
    <tr>
        <th><%= f.label :title ,"タイトル" %></th>
        <td><%= f.text_field :title %></td>
    </tr>
    <tr>
        <th><%= f.label :start_date ,"開始日" %></th>
        <td><%= f.date_select :start_date %></td>
    </tr>
    <tr>
        <th><%= f.label :end_date ,"終了日" %></th>
        <td><%= f.date_select :end_date %></td>
    </tr>
    <tr>
        <th><%= f.label :all_day ,"終日" %></th>
        <td><%= f.check_box :all_day %>
            <p>※終日の場合はチェックを入れます</p>
        </td>
    </tr>
    <tr>
        <th><%= f.label :memo ,"スケジュールメモ" %></th>
        <td><%= f.text_area :memo %></td>
    </tr>
</table>

<div>
    <ul>
        <li><%= f.submit "スケジュールを新規登録する"%></li>
        <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
    </ul>
</div>
<% end %>

app/views/schedules/show.html.erb
<%= render "shared/header" %>

<h3>スケジュール詳細</h3>

<table>
    <tr>
        <th>タイトル</th>
        <td><%= @schedule.title %></td>
    </tr>
    <tr>
        <th>開始日</th>
        <td><%= @schedule.start_date %></td>
    </tr>
    <tr>
        <th>終了日</th>
        <td><%= @schedule.end_date %></td>
    </tr>
    <tr>
        <th>終日</th>
        <td>
            <%if @schedule.all_day %>
            <% end %>
        </td>
    </tr>
    <tr>
        <th>スケジュールメモ</th>
        <td><%= @schedule.memo %></td>
    </tr>
</table>

<div>
    <ul>
        <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
        <li><%= link_to "このスケジュールを編集", [:edit, @schedule] %></li>
        <li><%= link_to "このスケジュールを削除する", @schedule, data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }%></li>
    </ul>
</div>

<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<footer>
    <h1>現在の日時：<%= Date.today%> スケジュールの合計：<%= Schedule.count %></h1>
</footer>

app/views/shared/_header.html.erb
<header>
    <h1>Ruby on Rails スケジュール管理アプリ</h1>
</header>